version: '3.0'
services:
  syncthing:
    image: syncthing/syncthing
    security_opt:
      - no-new-privileges:true
    environment:
      FILE__TZ: "America/New_York"
    volumes:
      - /opt/containers/st-sync:/var/syncthing
    ##            - {{ photostructure.library_path }}:/ps/library:rw
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
