#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
    
write_files:
  ## photostructure/docker-compose.yaml sets up the Docker container for Photostructure
  - path: /opt/containers/templates/sftp/docker-compose.yaml.j2
    content: |
      version: '3.0'
      
      services:
        sftp:
          image: atmoz/sftp
          volumes:
            - {{ sftp.config_root }}:/etc/ssh/ssh_host_ed25519_key
            - {{ sftp.config_root }}:/etc/ssh/ssh_host_rsa_key
            - /host/share:/home/foo/share
          ports:
            - "{{ sftp.port }}:22"
          command: foo::1001
          
  - path: /opt/containers/templates/sftp/keys.sh.j2
    content: |
      ##Tip: you can generate your keys with these commands:
      ssh-keygen -t ed25519 -f {{ sftp.config_root }}/ssh_host_ed25519_key < /dev/null
      ssh-keygen -t rsa -b 4096 -f {{ sftp.config_root }}/ssh_host_rsa_key < /dev/null

          

runcmd:
  - mkdir -p /opt/containers/sftp 
  ## Render the keys.sh from the template:
  - j2 /opt/containers/templates/sftp/keys.sh.j2 /run/cloud-init/user-variables-sensitive.yaml | /bin/bash
  ## Render the docker-compose from the template:
  - j2 /opt/containers/templates/sftp/docker-compose.yaml.j2 /run/cloud-init/user-variables-sensitive.yaml -o /opt/containers/sftp/docker-compose.yaml
  ## Create and start the containers
  - docker-compose -f /opt/containers/sftp/docker-compose.yaml up -d
  
