#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
    
write_files:
  ## photostructure/docker-compose.yaml sets up the Docker container for Photostructure
  - path: /opt/containers/templates/sftp/docker-compose.yaml.j2
    content: |
      version: '3.0'
      
      services:
        sftp:
          image: atmoz/sftp
          volumes:
            - {{ sftp.config_root }}/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
            - {{ sftp.config_root }}/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
        {% for u in sftp.users %}
          {% for share in u["shares"] %}
            - {{ share["host"] }}:/home/{{ u["name"] }}/{{ share["name"] }}
          {% endfor %}
            - /opt/containers/sftp/data/{{ u["name"] }}/.ssh:/home/{{ u["name"] }}/.ssh
        {% endfor %}
            - /opt/containers/sftp/data/users.conf:/etc/sftp/users.conf
          ports:
            - "{{ sftp.port }}:22"
          
  - path: /opt/containers/templates/sftp/setup.sh.j2
    content: |
      mkdir -p {{ sftp.config_root }}
      ssh-keygen -t ed25519 -f {{ sftp.config_root }}/ssh_host_ed25519_key < /dev/null
      ssh-keygen -t rsa -b 4096 -f {{ sftp.config_root }}/ssh_host_rsa_key < /dev/null
      ## for each user...
      {% for u in sftp.users %}
        ## write their public key to their own directory
        mkdir -p /opt/containers/sftp/data/{{ u["name"] }}/.ssh/keys
        echo '{{ u["pubkey"] }}' > /opt/containers/sftp/data/{{ u["name"] }}/.ssh/keys/id_rsa.pub
        ## also add them to users.conf
        echo '{{ u["name"] }}::{{ u["uid"] }}:{{ u["gid"] }}:{{ u["name"] }}' >> /opt/containers/sftp/data/users.conf
        ## and create and chown each of their shares
        {% for share in u["shares"] %}
          mkdir -p {{ share["host"] }}
          chown {{ u["uid"] }} {{ share["host"] }}
        {% endfor %}
      {% endfor %}
    
runcmd:
  - mkdir -p /opt/containers/sftp/data
  ## Render and execute keys.sh from the template:
  - j2 /opt/containers/templates/sftp/setup.sh.j2 /run/cloud-init/user-variables-sensitive.yaml | /bin/bash
  ## Render the docker-compose from the template:
  - j2 /opt/containers/templates/sftp/docker-compose.yaml.j2 /run/cloud-init/user-variables-sensitive.yaml -o /opt/containers/sftp/docker-compose.yaml
  ## Create and start the containers
  - docker-compose -f /opt/containers/sftp/docker-compose.yaml up -d
