#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
 
write_files:
  ## syncthing/docker-compose.yaml sets up the Docker container for Syncthing
  - path: /opt/containers/templates/syncthing/docker-compose.yaml.j2
    content: |
      version: '3.0'

      services:
        syncthing:
          image: syncthing/syncthing
          security_opt:
            - no-new-privileges:true
          volumes:
            - /opt/containers/syncthing/data:/var/syncthing
          {% for v in volumes %}
            - {{ v["host"] }}:{{ v["container"] }}
          {% endfor %}
          ports:
            - 127.0.0.1:8384:8384
            - {{ syncthing.listen_port }}:22000
            - {{ syncthing.discovery_port }}:21027/udp
          restart: unless-stopped

runcmd:
  - mkdir -p /opt/containers/syncthing
  ## Render the docker-compose from the template:
  - j2 /opt/containers/templates/syncthing/docker-compose.yaml.j2 /run/cloud-init/user-variables-sensitive.yaml -o /opt/containers/syncthing/docker-compose.yaml
  ## Create and start the containers
  - docker-compose -f /opt/containers/syncthing/docker-compose.yaml up -d
