#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
 
write_files:
  ## syncthing/docker-compose.yaml sets up the Docker container for Syncthing
  - path: /opt/containers/templates/syncthing/docker-compose.yaml.j2
    content: |
      version: '3.0'

      services:
        syncthing:
          image: syncthing/syncthing
          security_opt:
            - no-new-privileges:true
          environment:
            FILE__TZ: "America/New_York"
            UMASK_SET: <022>
          volumes:
            - /opt/containers/st-sync:/var/syncthing
            - /storage/photos:/storage/photos
          ports:
            - {{ syncthing.webui_port_ext }}:{{ syncthing.webui_port_int }}
            - {{ syncthing.listen_port_ext }}:{{ syncthing.listen_port_int }}
            - {{ syncthing.discovery_port_ext }}:{{ syncthing.discovery_port_int }}/udp
          restart: unless-stopped
      networks:
        proxy:
          external: true

runcmd:
  - mkdir -p /opt/containers/st-sync
  ## Render the docker-compose from the template:
  - j2 /opt/containers/templates/syncthing/docker-compose.yaml.j2 /run/cloud-init/user-variables-sensitive.yaml -o /opt/containers/st-sync/docker-compose.yaml
  ## Create and start the containers
  - docker-compose -f /opt/containers/st-sync/docker-compose.yaml up -d
