#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

write_files:
  - path: /opt/containers/templates/volumes/volumes_mount.sh.j2
    content: |
      #!/bin/sh
      set -e
      {% for v in volumes %}
        mkdir -p {{ v["mount"] }}
        mount -o discard,defaults /dev/disk/by-id/scsi-0DO_Volume_{{ v["name"] }} {{ v["mount"] }}
        echo /dev/disk/by-id/scsi-0DO_Volume_{{ v["name"] }} {{ v["mount"] }} {{ v["fs_type"] }} defaults,nofail,discard 0 0 | sudo tee -a /etc/fstab
      {% endfor %}

packages:
  - python3-pip
 
runcmd:
  - pip3 install j2cli[yaml]
  - j2 /opt/containers/templates/volumes/volumes_mount.sh.j2 /run/cloud-init/user-variables-sensitive.yaml | /bin/bash
